"""add product description

Revision ID: 5b372d90887c
Revises: 55529bc3b261
Create Date: 2026-05-23 23:04:39.422821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b372d90887c'
down_revision: Union[str, None] = '55529bc3b261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # SQLite: fill existing rows via server_default, then keep NOT NULL
    op.add_column(
        "products",
        sa.Column(
            "description",
            sa.String(length=500),
            nullable=False,
            server_default="",
        ),
    )
    op.execute(
        "UPDATE products SET description = title || ' (no description yet)' "
        "WHERE description = '' OR description IS NULL"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
